### ISSUE TITLE
Doesn't work well with HEAD version of tmux

### ISSUE THREAD

**Issue by demon386** [tony/tmuxp#120]
When using HEAD version of tmux, I fail to load the second YAML for tmuxp.

E.g.
1. Initially, tmux has no session.
2. tmuxp load xxx.yaml -> OK
3. tmuxp load yyy.yaml ->
   ```
   Session name yyy is already running. Attach? [Y/n]
   ```
   Actually this session is **NOT** already running.

   Pressing "Y", I got
   ```
  File "/usr/local/bin/tmuxp", line 9, in <module>
    load_entry_point('tmuxp==0.9.1', 'console_scripts', 'tmuxp')()
  File "/Library/Python/2.7/site-packages/tmuxp/cli.py", line 968, in main
    command_load(args)
  File "/Library/Python/2.7/site-packages/tmuxp/cli.py", line 422, in command_load
    load_workspace(file_user, args)
  File "/Library/Python/2.7/site-packages/tmuxp/cli.py", line 295, in load_workspace
    builder.session.attach_session()
AttributeError: 'NoneType' object has no attribute 'attach_session'
   ```

**Comment by tony** [comment]
we'll switch back travis to test against tmux latest git again

**Comment by tony** [comment]
Thank you for spotting this!

Regarding your experience in particular, 0.9.2 is updated to work with tmux 2.1.

Our travis builds are testing against tmux' git master once again.
